### PR TITLE
support maos m chip mps.  unet model dtype selection default

### PR DESCRIPTION
**Pull request by vanlew**
support maos m chip mps. 

unet model dtype selection default

### CODE REVIEW

**Comment by jet3004** [comment]
Does this have issues working on Mac? Getting _Error occurred when executing XlabsSampler: | Torch not compiled with CUDA enabled_ when trying to use Canny V2, for instance...

**Comment by pphoto808** [comment]
The issue is the XLabs Sampler does not work with Mac, regardless of dtype. Mac Studio M2 Ultra.

**Comment by alexgenovese** [comment]
Screenshot 2024-08-21 alle 08 06 17

they still use the get_torch_device() yet....

**Comment by pphoto808** [comment]
This is the workflow I'm trying and have issues with. If i use the default KSampler, the workflow works. But not with the XLabs-Sampler. I get the following:
Error occurred when executing XlabsSampler:

Torch not compiled with CUDA enabled

File "/Volumes/Extreme_Pro/pinokio/api/comfyui060924/app/execution.py", line 316, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/Volumes/Extreme_Pro/pinokio/api/comfyui060924/app/execution.py", line 191, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/Volumes/Extreme_Pro/pinokio/api/comfyui060924/app/execution.py", line 168, in _map_node_over_list
process_inputs(input_dict, i)
File "/Volumes/Extreme_Pro/pinokio/api/comfyui060924/app/execution.py", line 157, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/Volumes/Extreme_Pro/pinokio/api/comfyui060924/app/custom_nodes/x-flux-comfyui/nodes.py", line 289, in sampling
if torch.cuda.is_bf16_supported():
File "/Volumes/Extreme_Pro/pinokio/api/comfyui060924/app/env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 128, in is_bf16_supported
device = torch.cuda.current_device()
File "/Volumes/Extreme_Pro/pinokio/api/comfyui060924/app/env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 778, in current_device
_lazy_init()
File "/Volumes/Extreme_Pro/pinokio/api/comfyui060924/app/env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
raise AssertionError("Torch not compiled with CUDA enabled")


Screenshot 2024-08-20 at 20 31 18

**Comment by kensiu7** [comment]
Method not working, M1 max 

Error occurred when executing XlabsSampler:

Torch not compiled with CUDA enabled

  File "/Users/jianxiao/AI/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianxiao/AI/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianxiao/AI/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianxiao/AI/ComfyUI/custom_nodes/x-flux-comfyui/nodes.py", line 304, in sampling
    if torch.cuda.is_bf16_supported():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianxiao/enter/lib/python3.12/site-packages/torch/cuda/__init__.py", line 128, in is_bf16_supported
    device = torch.cuda.current_device()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianxiao/enter/lib/python3.12/site-packages/torch/cuda/__init__.py", line 778, in current_device
    _lazy_init()
  File "/Users/jianxiao/enter/lib/python3.12/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")

**Pull request closed without merging**
